twitter/urls.py
from django.urls import path
from twitter import views

app_name = 'twitter'

urlpatterns = [
    path('', views.MainWebPageView.as_view(), name="index"),
    path('compose/', views.TweetComposeView.as_view(), name="compose"),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('tweet/<int:pk>/', views.TweetDetailView.as_view(),
         name='tweet-detail'),
    path('user/<int:pk>/', views.AuthorDetailView.as_view(),
         name='author-detail'),
    path('message/', views.MessageListView.as_view(), name='messages'),
    path('message/<int:pk>', views.MessageDetailView.as_view(),
         name='message-detail'),
    path('message/new/', views.ComposeMessageView.as_view(),
         name='compose-message'),
]

twitter/models.py
from django.db import models
from django.contrib.auth.models import User

TWITTER_MAXIMUM_TWEET_LENGTH = 280
TWITTER_MAXIMUM_COMMENT_LENGTH = 60
TWITTER_MAXIMUM_MSG_LENGTH = 64


class Tweet(models.Model):
    content = models.CharField(max_length=TWITTER_MAXIMUM_TWEET_LENGTH)
    creation_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return '[{}] TWEET by {}: {}'.format(
            self.creation_date,
            self.author, self.content[:20])


class Comment(models.Model):
    content = models.CharField(max_length=TWITTER_MAXIMUM_COMMENT_LENGTH)
    date_comment = models.DateTimeField(auto_now_add=True)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content


class Message(models.Model):
    title = models.CharField(max_length=TWITTER_MAXIMUM_MSG_LENGTH)
    content = models.TextField()
    date_send = models.DateTimeField(auto_now_add=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="user_from")
    recipient = models.ForeignKey(User, on_delete=models.CASCADE,
                                  related_name="user_to")
    read = models.BooleanField(default=False)
    blocked = models.BooleanField(default=False)

    def __str__(self):
        return f'from: {self.sender} to: ' \
               f'{self.recipient} message: {self.content[0:20]}'

twitter/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from twitter import models


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class TweetForm(forms.ModelForm):
    class Meta:
        model = models.Tweet
        fields = ['content']
        widgets = {
            'content': forms.Textarea()
        }


class AddCommentForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 1, 'cols': 80}),
        max_length=models.TWITTER_MAXIMUM_COMMENT_LENGTH,
        label='')

    class Meta:
        model = models.Comment
        fields = ['content']
        labels = False


class MessageForm(forms.ModelForm):
    class Meta:
        model = models.Message
        fields = ['title', 'content', 'recipient']
        widgets = {
            'content': forms.Textarea()
        }

twitter/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django import views
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.models import User
from twitter import models
from twitter import forms
from .forms import UserRegisterForm


class MainWebPageView(views.View):

    def get(self, request):
        tweets = models.Tweet.objects.order_by('-creation_date').all()
        ctx = {
            'tweets': tweets
        }
        return render(request, 'twitter/index.html', ctx)


class TweetComposeView(LoginRequiredMixin, CreateView):
    model = models.Tweet
    form_class = forms.TweetForm
    success_url = reverse_lazy('twitter:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RegisterView(views.View):

    def get(self, request):
        form = UserRegisterForm()
        return render(request, 'twitter/register.html', {'form': form})

    def post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'{username} Konto zostało utworzone! Zaloguj się')
            return redirect('twitter:login')

        return render(request, 'twitter/register.html', {'form': form})


class ProfileView(LoginRequiredMixin, views.View):

    def get(self, request):
        tweets = models.Tweet.objects.filter(
            author=request.user).order_by('-creation_date')
        return render(request, 'twitter/profile.html', {'tweets': tweets})


class TweetDetailView(LoginRequiredMixin, views.View):

    def get(self, request, pk):
        tweet = models.Tweet.objects.get(pk=pk)
        add_comment_form = forms.AddCommentForm()
        return render(request, 'twitter/tweet_detail.html',
                      {'tweet': tweet, 'add_comment_form': add_comment_form})

    def post(self, request, pk):
        form = forms.AddCommentForm(request.POST)
        tweet = models.Tweet.objects.get(pk=pk)
        if form.is_valid():
            content = form.cleaned_data.get('content')
            new_comment = models.Comment(
                content=content, author=request.user, tweet=tweet)
            new_comment.save()
            form = forms.AddCommentForm()

        return render(request, 'twitter/tweet_detail.html',
                      {'tweet': tweet, 'add_comment': form})


class AuthorDetailView(views.View):

    def get(self, request, pk):
        author = User.objects.get(pk=pk)
        tweets = models.Tweet.objects.filter(
            author=author).order_by('-creation_date')
        return render(request, 'twitter/user_detail.html',
                      {'tweets': tweets, 'author': author})


class MessageListView(LoginRequiredMixin, views.View):

    def get(self, request):
        received = models.Message.objects.filter(
            recipient=request.user, blocked=False).order_by('-date_send')
        sent = models.Message.objects.filter(
            sender=request.user, blocked=False).order_by('-date_send')
        return render(request, 'twitter/messages.html',
                      {'received': received, 'sent': sent})


class ComposeMessageView(LoginRequiredMixin, CreateView):
    model = models.Message
    form_class = forms.MessageForm
    success_url = reverse_lazy('twitter:messages')

    def form_valid(self, form):
        form.instance.sender = self.request.user
        return super().form_valid(form)


class MessageDetailView(LoginRequiredMixin, views.View):

    def get(self, request, pk):
        query_set = models.Message.objects.filter(
            blocked=False).filter(
            Q(recipient=request.user) | Q(sender=request.user))
        msg = get_object_or_404(query_set, pk=pk)
        if msg.recipient.pk == request.user.pk:
            msg.read = True
            msg.save()

        return render(request, 'twitter/message_detail.html',
                      {'msg': msg})

twitter/templates/twitter/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link rel="stylesheet" type="text/css" href="{% static 'twitter/main.css' %}">
   <title>Django Twitter clone</title>
</head>

<body>
   <header class="site-header">
     <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
       <div class="container">
         <a class="navbar-brand mr-4" href="{% url 'twitter:index' %}">TwitterToo</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarToggle">
           <div class="navbar-nav mr-auto">
             <a class="nav-item nav-link" href="{% url 'twitter:index' %}">Home</a>
           </div>
           <!-- Navbar Right Side -->
           <div class="navbar-nav">
               {% if user.is_authenticated %}
                   <a class="nav-item nav-link" href="{% url 'twitter:compose' %}">New Post</a>
                   <a class="nav-item nav-link" href="{% url 'twitter:messages' %}">Inbox</a>
                   <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
               {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'twitter:register' %}">Register</a>
               {% endif %}
           </div>
         </div>
       </div>
     </nav>
   </header>
    <div class="container">
   {% block content %}
   {% endblock %}
    </div>

   <!-- Optional JavaScript -->
   <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

twitter/templates/twitter/index.html
{% extends 'twitter/base.html' %}
{% load avatar_tags %}
{% block content %}
    {% for tweet in tweets %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    {% avatar tweet.author 25 class="rounded-circle" id="user_avatar" %}
                    <a href="{% url 'twitter:tweet-detail' tweet.pk %}">
                        <small class="text-muted">{{ tweet.creation_date|date:"F d, Y" }}</small>
                    </a>
                    <a href="{% url 'twitter:author-detail' tweet.author.pk %}">
                        <small class="text-muted">by {{ tweet.author }}</small>
                    </a>
                </div>
                <p class="article-content">{{ tweet.content }}</p>
                <div>
                    {% if tweet.comment_set.all %}
                        <small class="text-muted">Comments: ({{ tweet.comment_set.all.count }})</small><br>
                        {% for comment in tweet.comment_set.all %}
                            {% avatar comment.author 25 class="rounded-circle" id="user_avatar" %}
                            <small class="text-muted">{{ comment.author.username }}: </small>
                            {{ comment.content|truncatechars:25 }}<br>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

twitter/templates/twitter/login.html
{% extends 'twitter/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
                <small class="text-muted ml-2">
                    <a href="{% url 'password-reset' %}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an Account? <a class="ml-2" href="{% url 'twitter:register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

twitter/templates/twitter/logout.html
{% extends 'twitter/base.html' %}
{% block content %}
    <div class="container">
        <h2>Zostałeś wylogowany</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'login' %}">Zaloguj się ponownie</a>
            </small>
        </div>
    </div>
{% endblock %}

twitter/templates/twitter/message_detail.html
{% extends 'twitter/base.html' %}
{% load avatar_tags %}
{% load crispy_forms_tags %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                FROM: <small class="text-muted">{% avatar msg.sender 25 class="rounded-circle" id="user_avatar" %} {{ msg.sender }}</small>
                TO: <small class="text-muted">{% avatar msg.recipient 25 class="rounded-circle" id="user_avatar" %} {{ msg.recipient }}</small>
                <small class="text-muted">{{ msg.date_send|date:"F d, Y" }}</small>
            </div>
            <h2 class="article-title">{{ msg.title }}</h2>
            <p class="article-content">{{ msg.content }}</p>
        </div>
    </article>
{% endblock content %}

twitter/templates/twitter/message_form.html
{% extends 'twitter/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">New message</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sent</button>
            </div>
        </form>
    </div>
{% endblock content %}

twitter/templates/twitter/messages.html
{% extends 'twitter/base.html' %}
{% load avatar_tags %}
{% block content %}
    <h1>Messages</h1>
    <a class="btn btn-outline-info" href="{% url 'twitter:compose-message' %}">New message</a>
    <p></p>
    {% block messages %}
        <h2>Received messages</h2>
        {% if received %}
            {% for message in received %}
                <article class="media content-section">
                    <div class="media-body">
                        <div class="article-metadata">
                            From: <a class="mr-2" href="{% url 'twitter:author-detail' message.sender.pk %}">
                            {% avatar message.sender 25 class="rounded-circle" id="user_avatar" %} {{ message.sender }}</a>
                            <small class="text-muted">{{ message.date_send|date:"F d, Y" }}</small>
                        </div>
                        <div class="article-metadata">
                            {% if not message.read %}
                                <b><a href="{% url 'twitter:message-detail' message.pk %}">{{ message.title }}</a></b>
                            {% else %}
                                <a href="{% url 'twitter:message-detail' message.pk %}">{{ message.title }}</a>
                            {% endif %}
                        </div>
                    </div>
                </article>
            {% endfor %}
        {% else %}
            <p>Your mailbox is empty</p>
        {% endif %}
        <h2>Sent messages</h2>
        {% if sent %}
            {% for message in sent %}
                <article class="media content-section">
                    <div class="media-body">
                        <div class="article-metadata">
                            To: <a class="mr-2"
                                   href="{% url 'twitter:author-detail' message.recipient.pk %}">
                            {% avatar message.recipient 25 class="rounded-circle" id="user_avatar" %} {{ message.recipient }}</a>
                            <small class="text-muted">{{ message.date_send|date:"F d, Y" }}</small>
                        </div>
                        <div class="article-metadata">
                            <a href="{% url 'twitter:message-detail' message.pk %}">{{ message.title }}</a>
                        </div>
                    </div>
                </article>
            {% endfor %}
        {% else %}
            <p>No messages sent.
                <a href="{% url 'twitter:compose-message' %}">Send a new message</a>
            </p>
        {% endif %}
    {% endblock messages %}
{% endblock content %}

twitter/templates/twitter/password_reset.html
{% extends 'twitter/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

twitter/templates/twitter/profile.html
{% extends 'twitter/base.html' %}
{% load avatar_tags %}
{% block content %}
{% avatar user 65 class="rounded-circle" id="user_avatar" %}
<a href="{% url 'avatar_change' %}">Change your avatar</a>
<h2>Tweets by {{ user.get_username }}</h2>
    {% for tweet in tweets %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <small class="text-muted">{{ tweet.creation_date|date:"F d, Y" }}</small>
                </div>
                <p class="article-content">{{ tweet.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

twitter/templates/twitter/register.html
{% extends 'twitter/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Dodaj Użytkownika</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Dodaj</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Posiadasz konto?<a class="ml-2" href="{% url 'login' %}">Zaloguj się</a>
            </small>
        </div>
    </div>
{% endblock %}

twitter/templates/twitter/tweet_detail.html
{% extends 'twitter/base.html' %}
{% load crispy_forms_tags %}
{% load avatar_tags %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                {% avatar tweet.author 25 class="rounded-circle" id="user_avatar" %}
                <small class="text-muted">{{ tweet.author }}</small>
                <small class="text-muted">{{ tweet.creation_date|date:"F d, Y" }}</small>
            </div>
            <p class="article-content">{{ tweet.content }}</p>
            <form action="#" method="POST">
                {% csrf_token %}
                    <small class="text-muted">Add comment:</small>
                    <small class="text-muted">{{ add_comment_form|crispy }}</small>
                    <button class="btn btn-outline-info" type="submit">Add</button>
            </form>
            <div>
                {% if tweet.comment_set.all %}
                    <small class="text-muted">Comments: ({{ tweet.comment_set.all.count }})</small><br>
                {% for comment in tweet.comment_set.all %}
                   <small class="text-muted">{{ comment.author.username }}: </small>{{ comment.content }}<br>
                {% endfor %}
                {% else %}
                    <small class="text-muted">Be the first to comment.</small>
               {% endif %}
            </div>
        </div>
    </article>
{% endblock content %}

twitter/templates/twitter/tweet_form.html
{% extends 'twitter/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">What's going on, {{user}}?</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

twitter/templates/twitter/user_detail.html
{% extends 'twitter/base.html' %}
{% load avatar_tags %}
{% block content %}
<h2>Tweets by {% avatar author 25 class="rounded-circle" id="user_avatar" %} {{ author.get_username }}</h2>
    {% for tweet in tweets %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <small class="text-muted">{{ tweet.creation_date|date:"F d, Y" }}</small>
                </div>
                <p class="article-content">{{ tweet.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}